const scams = [
  {
    id: 'financial-document-scheme',
    category: 'consumer-scams',
    title: 'Financial Document Scheme',
    description: 'A common scam involving financial documents. Users may receive a .zip or .rar file containing malicious JavaScript.',
    example: 'Users may be tricked into expanding the file and executing the malicious JavaScript, which can compromise their system.',
    solution: 'Be cautious when receiving unexpected files, especially from unknown sources. Always verify the authenticity of the sender and scan files for malware before opening them.',
    image: 'financial_document_scheme.jpg',
  },
  {
    id: 'discord-verification-scam',
    category: 'consumer-scams',
    title: 'Discord Verification Scam',
    description: 'A scam targeting Discord users by directing them to a page with JavaScript commands.',
    example: 'Users may be instructed to run JavaScript code that performs unauthorized actions or compromises their system.',
    solution: 'Exercise caution when following instructions from unknown sources, especially when executing JavaScript code. Only run code from trusted sources.',
    image: 'discord_verification_scam.jpg',
  },
  {
    id: 'encrypted-javascript-scam',
    category: 'consumer-scams',
    title: 'Encrypted JavaScript Scam',
    description: 'Scammers use encrypted and obfuscated JavaScript code on phishing and malicious websites.',
    example: 'The use of encryption and obfuscation makes it difficult to determine the actual actions performed by the JavaScript code.',
    solution: 'Be cautious when visiting unfamiliar websites and avoid executing JavaScript code from untrusted sources.',
    image: 'encrypted_javascript_scam.jpg',
  },
  {
    id: 'imposter-scams',
    category: 'consumer-scams',
    title: 'Imposter Scams',
    description: 'Imposter scams involve someone pretending to be someone they are not to extract money or personal information from their victims.',
    example: 'Scammers may impersonate government officials, company representatives, or family members to deceive victims.',
    solution: 'Be skeptical of unsolicited requests for money or personal information. Verify the identity of the person contacting you through independent means.',
    image: 'imposter_scams.jpg',
  },
  {
    id: 'online-shopping-scams',
    category: 'consumer-scams',
    title: 'Online Shopping Scams',
    description: 'Online shopping scams involve fraudulent schemes on e-commerce platforms or fake online stores.',
    example: 'Scammers may advertise products at extremely low prices or create fake websites that mimic legitimate online stores.',
    solution: 'Shop only from reputable and secure websites. Be cautious of deals that seem too good to be true and research the seller before making a purchase.',
    image: 'online_shopping_scams.jpg',
  },
  {
    id: 'business-email-compromise',
    category: 'business-scams',
    title: 'Business Email Compromise',
    description: 'Business email compromise (BEC) scams involve impersonating a business or executive to trick employees into making unauthorized payments or sharing sensitive information.',
    example: 'Scammers may send emails that appear to be from a company executive, requesting urgent wire transfers or confidential data.',
    solution: 'Implement strong email security measures, such as multi-factor authentication and employee training to recognize and report suspicious emails.',
    image: 'business_email_compromise.jpg',
  },
  {
    id: 'phishing-scams',
    category: 'business-scams',
    title: 'Phishing Scams',
    description: 'Phishing scams use fake emails or websites to trick individuals into revealing sensitive information, such as login credentials or financial data.',
    example: 'Scammers may send emails that appear to be from reputable organizations, asking recipients to update their account information or verify their identity.',
    solution: 'Exercise caution when clicking on links or providing personal information in response to unsolicited emails. Verify the legitimacy of the sender and website before sharing any sensitive information.',
    image: 'phishing_scams.jpg',
  },
  // Add more scams here
];