const scams = [
  {
    id: 'phishing',
    title: 'Phishing',
    description: 'Les escroqueries de phishing impliquent de faux e-mails ou sites web qui trompent les utilisateurs pour obtenir des informations sensibles.',
    example: 'Les escrocs peuvent se faire passer pour des entreprises ou des individus légitimes afin de tromper les victimes et les inciter à divulguer leurs identifiants de connexion, leurs informations financières ou d\'autres données personnelles.',
    solution: 'Soyez prudent lorsque vous cliquez sur des liens dans les e-mails et vérifiez toujours l\'identité de l\'expéditeur avant de fournir des informations sensibles.',
    image: 'phishing.jpg',
  },
  {
    id: 'identity-theft',
    title: 'Vol d\'identité',
    description: 'Le vol d\'identité se produit lorsque quelqu\'un vole vos informations personnelles pour commettre une fraude ou d\'autres crimes.',
    example: 'Les criminels peuvent utiliser vos informations volées pour ouvrir de nouveaux comptes, effectuer des achats ou déposer des déclarations de revenus frauduleuses en votre nom.',
    solution: 'Surveillez régulièrement vos rapports de crédit, utilisez des mots de passe forts et soyez prudent lorsque vous partagez des informations personnelles en ligne.',
    image: 'identity_theft.jpg',
  },
  {
    id: 'investment-scams',
    title: 'Escroqueries d\'investissement',
    description: 'Les escroqueries d\'investissement impliquent des schémas frauduleux qui promettent des rendements élevés avec peu ou pas de risque.',
    example: 'Les escrocs peuvent vous appeler ou vous envoyer des e-mails avec des opportunités d\'investissement qui semblent trop belles pour être vraies, ou vous mettre sous pression pour investir rapidement avant que l\'opportunité ne disparaisse.',
    solution: 'Faites des recherches avant d\'investir et méfiez-vous des offres d\'investissement non sollicitées ou des tactiques de vente sous pression.',
    image: 'investment_scams.jpg',
  },
  {
    id: 'pyramid-schemes',
    title: 'Systèmes de Ponzi',
    description: 'Les systèmes de Ponzi impliquent de recruter de nouveaux membres pour gagner de l\'argent, plutôt que de vendre un produit ou un service légitime.',
    example: 'Les escrocs peuvent promettre de gros profits pour recruter de nouveaux membres, mais le système s\'effondre finalement lorsqu\'il n\'y a pas assez de nouveaux membres pour le maintenir.',
    solution: 'Évitez tout système qui vous oblige à recruter de nouveaux membres pour gagner de l\'argent et soyez méfiant envers toute opportunité qui promet de gros profits avec peu d\'efforts.',
    image: 'pyramid_schemes.jpg',
  },
  {
    id: 'fake-goods-scams',
    title: 'Escroqueries de faux produits',
    description: 'Les escroqueries de faux produits impliquent la vente de contrefaçons ou de produits falsifiés à un prix moins cher.',
    example: 'Les escrocs peuvent utiliser des publicités frauduleuses sur les réseaux sociaux ou les places de marché en ligne pour vendre des produits contrefaits, tels que des vêtements de marque, des appareils électroniques ou des produits pharmaceutiques.',
    solution: 'Achetez des produits uniquement auprès de vendeurs et de sites web réputés, et méfiez-vous des offres qui semblent trop belles pour être vraies.',
    image: 'fake_goods_scams.jpg',
  },
  {
    id: 'charity-scams',
    title: 'Escroqueries de charité',
    description: 'Les escroqueries de charité impliquent de se faire passer pour une organisation caritative légitime afin de solliciter des dons ou des informations personnelles.',
    example: 'Les escrocs peuvent proposer de faire vos courses ou de faire le ménage pour vous, ou demander des dons à une fausse organisation caritative. Vérifiez la légitimité de toute organisation caritative avant de faire un don ou de partager des informations personnelles, et méfiez-vous des demandes de dons non sollicitées.',
    solution: 'Vérifiez la légitimité de toute organisation caritative avant de faire un don ou de partager des informations personnelles, et méfiez-vous des demandes de dons non sollicitées.',
    image: 'charity_scams.jpg',
  },
  {
    id: 'tech-support-scams',
    title: 'Escroqueries de support technique',
    description: 'Les escroqueries de support technique impliquent de se faire passer pour une entreprise de support technique légitime afin de tromper les utilisateurs et de leur faire payer des services ou des logiciels inutiles.',
    example: 'Les escrocs peuvent appeler ou envoyer des messages pop-up prétendant que votre ordinateur est infecté par un virus ou un autre problème, et proposer de le réparer moyennant des frais. Ne fournissez aucune information personnelle ou financière aux appelants non sollicités ou aux messages pop-up, et utilisez un logiciel antivirus réputé pour protéger votre ordinateur.',
    solution: 'Ne fournissez aucune information personnelle ou financière aux appelants non sollicités ou aux messages pop-up, et utilisez un logiciel antivirus réputé pour protéger votre ordinateur.',
    image: 'tech_support_scams.jpg',
  },
  {
    id: 'fake-antivirus-software-scams',
    title: 'Escroqueries de faux logiciels antivirus',
    description: 'Les escroqueries de faux logiciels antivirus impliquent des publicités ou des pop-ups prétendant que votre ordinateur est infecté par un virus et proposant de le réparer avec leur logiciel.',
    example: 'Les escrocs peuvent utiliser des tactiques d\'intimidation pour vous faire croire que votre ordinateur est infecté par un virus ou un autre logiciel malveillant, et vous pousser à télécharger leur logiciel. Utilisez un logiciel antivirus réputé et ne téléchargez ni n\'installez aucun logiciel provenant de sources non sollicitées.',
    solution: 'Utilisez un logiciel antivirus réputé et ne téléchargez ni n\'installez aucun logiciel provenant de sources non sollicitées.',
    image: 'fake_antivirus_scams.jpg',
  }
];