const scams = [
  {
    id: 'fraude-financiere',
    category: 'malware',
    title: 'Fraude financière',
    description: "Une arnaque courante impliquant des documents financiers. Les utilisateurs peuvent recevoir un fichier .zip ou .rar contenant du code JavaScript malveillant.",
    example: "Les utilisateurs peuvent être trompés pour extraire le fichier et exécuter le code JavaScript malveillant, ce qui peut compromettre leur système.",
    solution: "Soyez prudent lorsque vous recevez des fichiers inattendus, en particulier en provenance de sources inconnues. Vérifiez toujours l'authenticité de l'expéditeur et analysez les fichiers à la recherche de logiciels malveillants avant de les ouvrir.",
    image: 'fraude_financiere.jpg',
  },
  {
    id: 'arnaque-verification-discord',
    category: 'phishing',
    title: 'Arnaque de vérification Discord',
    description: "Une arnaque ciblant les utilisateurs de Discord en les redirigeant vers une page contenant des commandes JavaScript.",
    example: "Les utilisateurs peuvent être incités à exécuter du code JavaScript qui effectue des actions non autorisées ou compromet leur système.",
    solution: "Faites preuve de prudence lorsque vous suivez des instructions provenant de sources inconnues, en particulier lors de l'exécution de code JavaScript. N'exécutez du code que provenant de sources fiables.",
    image: 'arnaque_verification_discord.jpg',
  },
  {
    id: 'arnaque-javascript-chiffre',
    category: 'phishing',
    title: 'Arnaque JavaScript chiffré',
    description: "Les escrocs utilisent du code JavaScript chiffré et obscurci sur des sites de phishing et des sites malveillants.",
    example: "L'utilisation du chiffrement et de l'obscurcissement rend difficile la détermination des actions réelles effectuées par le code JavaScript.",
    solution: "Soyez prudent lorsque vous visitez des sites Web inconnus et évitez d'exécuter du code JavaScript provenant de sources non fiables.",
    image: 'arnaque_javascript_chiffre.jpg',
  },
  {
    id: 'arnaques-impersonation',
    category: 'social-engineering',
    title: 'Arnaques d\'usurpation d\'identité',
    description: "Les arnaques d'usurpation d'identité impliquent quelqu'un se faisant passer pour quelqu'un d'autre afin d'obtenir de l'argent ou des informations personnelles de leurs victimes.",
    example: "Les escrocs peuvent se faire passer pour des fonctionnaires gouvernementaux, des représentants d'entreprise ou des membres de la famille pour tromper leurs victimes.",
    solution: "Soyez sceptique face aux demandes non sollicitées d'argent ou d'informations personnelles. Vérifiez l'identité de la personne qui vous contacte par des moyens indépendants.",
    image: 'arnaques_impersonation.jpg',
  },
  {
    id: 'arnaques-achat-en-ligne',
    category: 'phishing',
    title: 'Arnaques d\'achat en ligne',
    description: "Les arnaques d'achat en ligne impliquent des escroqueries sur des plateformes de commerce électronique ou de faux magasins en ligne.",
    example: "Les escrocs peuvent proposer des produits à des prix extrêmement bas ou créer de faux sites Web qui imitent des magasins en ligne légitimes.",
    solution: "Achetez uniquement sur des sites Web réputés et sécurisés. Méfiez-vous des offres qui semblent trop belles pour être vraies et recherchez le vendeur avant de faire un achat.",
    image: 'arnaques_achat_en_ligne.jpg',
  },
  {
    id: 'fraude-email-entreprise',
    category: 'phishing',
    title: 'Fraude par e-mail d\'entreprise',
    description: "La fraude par e-mail d'entreprise (BEC) implique l'usurpation d'une entreprise ou d'un cadre pour tromper les employés et les inciter à effectuer des paiements non autorisés ou à partager des informations sensibles.",
    example: "Les escrocs peuvent envoyer des e-mails qui semblent provenir d'un cadre de l'entreprise, demandant des virements urgents ou des données confidentielles.",
    solution: "Mettez en place des mesures de sécurité des e-mails solides, telles que l'authentification à deux facteurs et la sensibilisation des employés pour reconnaître et signaler les e-mails suspects.",
    image: 'fraude_email_entreprise.jpg',
  },
  {
    id: 'arnaques-phishing',
    category: 'phishing',
    title: 'Arnaques de phishing',
    description: "Les arnaques de phishing utilisent de faux e-mails ou sites Web pour tromper les individus et les inciter à divulguer des informations sensibles, telles que des identifiants de connexion ou des données financières.",
    example: "Les escrocs peuvent envoyer des e-mails qui semblent provenir d'organisations réputées, demandant aux destinataires de mettre à jour leurs informations de compte ou de vérifier leur identité.",
    solution: "Faites preuve de prudence lorsque vous cliquez sur des liens ou fournissez des informations personnelles en réponse à des e-mails non sollicités. Vérifiez l'authenticité de l'expéditeur et du site Web avant de partager des informations sensibles.",
    image: 'arnaques_phishing.jpg',
  },
  {
    id: 'arnaques-support-technique',
    category: 'social-engineering',
    title: 'Arnaques de support technique',
    description: "Les arnaques de support technique impliquent de faux services de support technique qui trompent les personnes en les faisant payer pour des réparations ou des logiciels inutiles.",
    example: "Les escrocs peuvent utiliser des messages pop-up ou des appels téléphoniques pour convaincre les victimes que leur ordinateur est infecté par un virus ou des logiciels malveillants.",
    solution: "Ne faites pas confiance aux messages pop-up non sollicités ou aux appels téléphoniques prétendant provenir du support technique. Utilisez uniquement des services de support technique fiables et réputés.",
    image: 'arnaques_support_technique.jpg',
  },
  {
    id: 'arnaques-cryptomonnaie',
    category: 'investment',
    title: 'Arnaques de cryptomonnaie',
    description: "Les arnaques de cryptomonnaie impliquent de fausses offres d'investissement en cryptomonnaie ou des échanges trompeurs qui incitent les gens à donner leur cryptomonnaie ou leurs informations personnelles.",
    example: "Les escrocs peuvent créer de faux échanges de cryptomonnaie ou des opportunités d'investissement qui promettent des rendements élevés avec peu ou pas de risque.",
    solution: "Méfiez-vous des opportunités d'investissement en cryptomonnaie non sollicitées ou des échanges trompeurs. Utilisez uniquement des services de cryptomonnaie fiables et réputés.",
    image: 'arnaques_cryptomonnaie.jpg',
  },
  {
    id: 'arnaques-emploi',
    category: 'social-engineering',
    title: 'Arnaques d\'emploi',
    description: "Les arnaques d'emploi impliquent de fausses offres d'emploi ou des opportunités de travail à domicile qui trompent les gens en les faisant payer pour une formation ou du matériel, ou en leur faisant divulguer des informations personnelles.",
    example: "Les escrocs peuvent annoncer de fausses offres d'emploi nécessitant un paiement pour une formation ou du matériel, ou demander des informations personnelles pour une vérification des antécédents.",
    solution: "Soyez prudent face aux offres d'emploi non sollicitées ou aux opportunités de travail à domicile. Recherchez l'entreprise et l'offre d'emploi avant de fournir des informations personnelles ou de faire un paiement.",
    image: 'arnaques_emploi.jpg',
  },
  {
    id: 'arnaques-charite',
    category: 'social-engineering',
    title: 'Arnaques de charité',
    description: "Les arnaques de charité impliquent de fausses organisations caritatives ou collectes de fonds qui trompent les gens en leur faisant don de l'argent qui n'est jamais utilisé à des fins caritatives.",
    example: "Les escrocs peuvent créer de fausses organisations caritatives ou collectes de fonds qui imitent des organisations ou des événements légitimes.",
    solution: "Recherchez l'organisation caritative ou la collecte de fonds avant de faire un don. Faites des dons uniquement à des organisations fiables et réputées.",
    image: 'arnaques_charite.jpg',
  },
  {
    id: 'arnaques-investissement',
    category: 'investment',
    title: 'Arnaques d\'investissement',
    description: "Les arnaques d'investissement promettent des rendements élevés sur les investissements avec peu ou pas de risque, mais sont en réalité des schémas frauduleux conçus pour voler de l'argent aux investisseurs.",
    example: "Les escrocs peuvent créer de fausses opportunités d'investissement qui promettent des rendements élevés avec peu ou pas de risque, ou utiliser des tactiques de vente sous pression pour convaincre les victimes d'investir.",
    solution: "Méfiez-vous des opportunités d'investissement non sollicitées ou des tactiques de vente sous pression. Investissez uniquement avec des sociétés d'investissement fiables et réputées.",
    image: 'arnaques_investissement.jpg',
  },
  {
    id: 'fraude-carte-credit',
    category: 'fraude',
    title: 'Fraude à la carte de crédit',
    description: "La fraude à la carte de crédit désigne toute activité illégale menée par des criminels ou des escrocs dans le but de subtiliser de l'argent sur les comptes de carte de crédit des victimes.",
    example: "Les fraudeurs peuvent voler les informations de carte de crédit des victimes en utilisant des techniques telles que le phishing, l'interception de données ou l'utilisation de dispositifs de skimming sur les terminaux de paiement.",
    solution: "Pour éviter la fraude à la carte de crédit, protégez toujours vos informations de carte de crédit, surveillez régulièrement vos relevés de compte, signalez immédiatement toute activité suspecte à votre banque et suivez les procédures de contestation des transactions frauduleuses.",
    image: 'fraude_carte_credit.jpg',
  },
    {
    id: 'arnaque-artisan',
    category: 'services',
    title: 'Arnaque d\'artisan',
    description: "Les artisans véreux peuvent escroquer les clients en fournissant des services de mauvaise qualité, en surfacturant ou en ne respectant pas les termes du contrat.",
    example: "Un artisan peut facturer des travaux non effectués, utiliser des matériaux de qualité inférieure ou ne pas respecter les délais convenus.",
    solution: "Recherchez des recommandations et des avis sur les artisans avant de les engager. Obtenez des devis détaillés et signez un contrat clair pour protéger vos droits en cas de litige.",
    image: 'arnaque_artisan.jpg',
  },
  {
    id: 'arnaque-démarchage-domicile',
    category: 'services',
    title: 'Arnaque de démarchage à domicile',
    description: "Les escrocs peuvent se faire passer pour des vendeurs ou des représentants de services à domicile pour tromper les résidents et leur vendre des produits ou des services inutiles ou de mauvaise qualité.",
    example: "Un démarcheur à domicile peut utiliser des tactiques de vente agressives, mentir sur les avantages ou les caractéristiques des produits, ou ne pas respecter les droits de rétractation des consommateurs.",
    solution: "Soyez méfiant envers les vendeurs à domicile non sollicités. Ne signez aucun contrat ou ne faites aucun paiement sous pression. Vérifiez toujours l'identité et la réputation de l'entreprise avant de faire un achat.",
    image: 'arnaque_demarchage_domicile.jpg',
  },
  {
    id: 'vente-forcée',
    category: 'services',
    title: 'Vente forcée',
    description: "La vente forcée consiste à contraindre les consommateurs à acheter des produits ou des services contre leur volonté, en utilisant des tactiques agressives ou trompeuses.",
    example: "Un vendeur peut insister pour que vous achetiez un produit ou un service supplémentaire, vous faire croire que c'est une offre limitée dans le temps ou vous mettre sous pression pour prendre une décision immédiate.",
    solution: "Sachez que vous avez le droit de refuser un achat et de prendre le temps de réfléchir avant de prendre une décision. Ne vous sentez pas obligé d'acheter quelque chose sous pression.",
    image: 'vente_forcee.jpg',
  }